// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCxDTwrioHD-xDAVqEsWtrrAJIdYE88TQ',
    appId: '1:1016631424538:web:d374c0a51487cccd4ec3a3',
    messagingSenderId: '1016631424538',
    projectId: 'food-vault-7b423',
    authDomain: 'food-vault-7b423.firebaseapp.com',
    storageBucket: 'food-vault-7b423.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz71MfVup3aJ_GU8y5uBHwDaGXO3UikEI',
    appId: '1:1016631424538:android:145cb4e8c62493784ec3a3',
    messagingSenderId: '1016631424538',
    projectId: 'food-vault-7b423',
    storageBucket: 'food-vault-7b423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnWhKLMoHMCxWb8YsucSLF7NJo-4hVdi4',
    appId: '1:1016631424538:ios:9fc193ed375f96c64ec3a3',
    messagingSenderId: '1016631424538',
    projectId: 'food-vault-7b423',
    storageBucket: 'food-vault-7b423.appspot.com',
    iosBundleId: 'com.example.virtualFoodStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnWhKLMoHMCxWb8YsucSLF7NJo-4hVdi4',
    appId: '1:1016631424538:ios:2574906635c21c674ec3a3',
    messagingSenderId: '1016631424538',
    projectId: 'food-vault-7b423',
    storageBucket: 'food-vault-7b423.appspot.com',
    iosBundleId: 'com.example.virtualFoodStorage.RunnerTests',
  );
}
